import type { UserProfile } from '@/lib/types';

// Mock members spread across major Indian cities for demo purposes
export const mockMembers: Omit<UserProfile, 'id'>[] = [
  {
    name: 'Arjun Mehta',
    email: 'arjun@techventures.in',
    profession: 'Startup Founder',
    company: 'TechVentures India',
    bio: 'Building the future of fintech in India. 3x founder, angel investor. Love connecting with fellow entrepreneurs over chai.',
    avatar: '',
    city: 'Mumbai',
    availability: 'Open to Meet',
    latitude: 19.076,
    longitude: 72.8777,
  },
  {
    name: 'Priya Sharma',
    email: 'priya@designlabs.co',
    profession: 'UX Director',
    company: 'DesignLabs',
    bio: 'Passionate about creating human-centered digital experiences. Previously at Flipkart and Swiggy.',
    avatar: '',
    city: 'Bangalore',
    availability: 'Available',
    latitude: 12.9716,
    longitude: 77.5946,
  },
  {
    name: 'Vikram Patel',
    email: 'vikram@cloudscale.io',
    profession: 'CTO',
    company: 'CloudScale Solutions',
    bio: 'Infrastructure nerd. Scaling systems to millions. Open source contributor and tech community builder.',
    avatar: '',
    city: 'Hyderabad',
    availability: 'Traveling',
    latitude: 17.385,
    longitude: 78.4867,
  },
  {
    name: 'Sneha Reddy',
    email: 'sneha@greeninvest.com',
    profession: 'Angel Investor',
    company: 'GreenInvest Capital',
    bio: 'Investing in climate tech and sustainable startups. Portfolio of 20+ companies across South Asia.',
    avatar: '',
    city: 'Chennai',
    availability: 'Available',
    latitude: 13.0827,
    longitude: 80.2707,
  },
  {
    name: 'Rahul Gupta',
    email: 'rahul@legaledge.in',
    profession: 'Legal Consultant',
    company: 'LegalEdge Partners',
    bio: 'Corporate law specialist focusing on startup compliance, fundraising, and IP protection.',
    avatar: '',
    city: 'Delhi',
    availability: 'Busy',
    latitude: 28.6139,
    longitude: 77.209,
  },
  {
    name: 'Ananya Krishnan',
    email: 'ananya@marketpulse.co',
    profession: 'Marketing Head',
    company: 'MarketPulse',
    bio: 'Growth marketing strategist. Helped 50+ startups achieve product-market fit through data-driven campaigns.',
    avatar: '',
    city: 'Pune',
    availability: 'Open to Meet',
    latitude: 18.5204,
    longitude: 73.8567,
  },
  {
    name: 'Karthik Nair',
    email: 'karthik@aiworks.dev',
    profession: 'AI Engineer',
    company: 'AI Works',
    bio: 'Machine learning engineer specializing in NLP and computer vision. Building AI solutions for healthcare.',
    avatar: '',
    city: 'Bangalore',
    availability: 'Available',
    latitude: 12.9352,
    longitude: 77.6245,
  },
  {
    name: 'Meera Joshi',
    email: 'meera@fundbridge.vc',
    profession: 'Venture Capitalist',
    company: 'FundBridge VC',
    bio: 'Early-stage VC focusing on B2B SaaS and deep tech. Always looking for bold founders building category-defining companies.',
    avatar: '',
    city: 'Mumbai',
    availability: 'Traveling',
    latitude: 19.0596,
    longitude: 72.8295,
  },
  {
    name: 'Aditya Singh',
    email: 'aditya@blockstack.io',
    profession: 'Blockchain Developer',
    company: 'BlockStack Labs',
    bio: 'Web3 builder and DeFi enthusiast. Contributing to decentralized finance protocols and blockchain infrastructure.',
    avatar: '',
    city: 'Gurgaon',
    availability: 'Open to Meet',
    latitude: 28.4595,
    longitude: 77.0266,
  },
  {
    name: 'Divya Menon',
    email: 'divya@hrconnect.in',
    profession: 'HR Director',
    company: 'TalentBridge',
    bio: 'People-first leader building inclusive workplaces. Expert in remote team building and organizational culture.',
    avatar: '',
    city: 'Kochi',
    availability: 'Available',
    latitude: 9.9312,
    longitude: 76.2673,
  },
  {
    name: 'Rohan Desai',
    email: 'rohan@supplychain.pro',
    profession: 'Operations Head',
    company: 'LogiFlow',
    bio: 'Supply chain optimization specialist. Helping D2C brands scale their logistics across India.',
    avatar: '',
    city: 'Ahmedabad',
    availability: 'Busy',
    latitude: 23.0225,
    longitude: 72.5714,
  },
  {
    name: 'Ishita Banerjee',
    email: 'ishita@contentcraft.co',
    profession: 'Content Strategist',
    company: 'ContentCraft',
    bio: 'Storyteller at heart. Building brand narratives for tech startups. Published author and TEDx speaker.',
    avatar: '',
    city: 'Kolkata',
    availability: 'Open to Meet',
    latitude: 22.5726,
    longitude: 88.3639,
  },
];
